feat: added transfers related services and test

diff --git a/docker-compose-perf.yml b/docker-compose-perf.yml
--- a/docker-compose-perf.yml
+++ b/docker-compose-perf.yml
@@ -56,6 +56,7 @@ services:
       - account-lookup-service
       - discovery
       - all-services
+      - als-test
 
   mysql-als:
     image: mysql/mysql-server
@@ -84,9 +85,200 @@ services:
       - account-lookup-service
       - discovery
       - all-services
+      - als-test
     ## In memory storage - Ref: https://docs.docker.com/storage/tmpfs/
     tmpfs:
       - /var/lib/mysql
+
+  ## Services for Transfer tests
+  central-ledger:
+    image: mojaloop/central-ledger:${CENTRAL_LEDGER_VERSION}
+    container_name: central-ledger
+    command: sh -c "/opt/app/config-modifier/run.js /opt/app/config/default.json /opt/app/config-modifier/configs/central-ledger.js /opt/app/config/default.json && /opt/app/wait4/wait4.js central-ledger && node src/api/index.js"
+    # ports:
+    #   - "3001:3001"
+    volumes:
+       - ./docker/wait4:/opt/app/wait4
+       - ./docker/config-modifier:/opt/app/config-modifier
+    environment:
+      - LOG_LEVEL=info
+      - CLEDG_MONGODB__DISABLED=false
+      - EVENT_SDK_TRACEID_PER_VENDOR=false
+    networks:
+      - mojaloop-net
+    depends_on:
+      mysql:
+        condition: service_started
+      kafka:
+        condition: service_started
+      objstore:
+        condition: service_started
+    healthcheck:
+      test: wget -q http://localhost:3001/health -O /dev/null || exit 1
+      timeout: 20s
+      retries: 30
+      interval: 30s
+      start_period: 30s
+    user: root
+    profiles:
+      - central-ledger
+      - transfer
+      - discovery
+      - agreement
+      - all-services
+      - transfers-test
+
+  objstore:
+    image: mongo:6.0.5
+    container_name: objstore
+    ports:
+      - "27017:27017"
+    networks:
+      - mojaloop-net
+    healthcheck:
+      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
+      interval: 10s
+      timeout: 10s
+      retries: 5
+      start_period: 40s
+    profiles:
+      - central-ledger
+      - transfer
+      - discovery
+      - agreement
+      - all-services
+      - transfers-test
+
+  kafka-provisioning:
+    container_name: kafka-provisioning
+    networks:
+      - mojaloop-net
+    image: docker.io/bitnami/kafka:3.4.0
+    depends_on:
+      - kafka
+    entrypoint: [ '/bin/sh', '-c' ]
+    command: |
+      "
+      # blocks until kafka is reachable
+      kafka-topics.sh --bootstrap-server kafka:29092 --list
+      echo -e 'Creating kafka topics'
+      kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic topic-transfer-prepare --replication-factor 1 --partitions 1
+      kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic topic-transfer-position --replication-factor 1 --partitions 1
+      kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic topic-transfer-fulfil --replication-factor 1 --partitions 1
+      kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic topic-notification-event --replication-factor 1 --partitions 1
+      kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic topic-transfer-get --replication-factor 1 --partitions 1
+      kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic topic-admin-transfer --replication-factor 1 --partitions 1
+      kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic topic-bulk-prepare --replication-factor 1 --partitions 1
+      kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic topic-bulk-fulfil --replication-factor 1 --partitions 1
+      kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic topic-bulk-processing --replication-factor 1 --partitions 1
+      kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic topic-bulk-get --replication-factor 1 --partitions 1
+      echo -e 'Successfully created the following topics:'
+      kafka-topics.sh --bootstrap-server kafka:29092 --list
+      "
+    profiles:
+      - central-ledger
+      - transfer
+      - discovery
+      - agreement
+      - all-services
+      - transfers-test
+
+  kafka:
+    networks:
+      - mojaloop-net
+    image: docker.io/bitnami/kafka:3.4.0
+    container_name: kafka
+    # ports:
+    #   - "9092:9092"
+    environment:
+      # BITNAMI_DEBUG: "yes"
+      ALLOW_PLAINTEXT_LISTENER: "yes"
+      KAFKA_ADVERTISED_HOST_NAME: kafka
+      KAFKA_CFG_LISTENERS: CONTROLLER://:9093,LISTENER_DOCKER://kafka:29092,LISTENER_EXTERN://:9092
+      KAFKA_CFG_ADVERTISED_LISTENERS: LISTENER_DOCKER://kafka:29092,LISTENER_EXTERN://:9092
+      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,LISTENER_DOCKER:PLAINTEXT,LISTENER_EXTERN:PLAINTEXT
+      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER
+      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
+      KAFKA_CFG_MESSAGE_MAX_BYTES: 200000000
+      KAFKA_CFG_NODE_ID: 1
+      KAFKA_CFG_PROCESS_ROLES: broker,controller
+      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
+      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
+      KAFKA_ENABLE_KRAFT: "true"
+    healthcheck:
+      test: ["CMD" ,"/opt/bitnami/kafka/bin/kafka-broker-api-versions.sh","--bootstrap-server","kafka:9092"]
+      timeout: 20s
+      retries: 10
+      start_period: 40s
+      interval: 30s
+    profiles:
+      - central-ledger
+      - transfer
+      - discovery
+      - agreement
+      - all-services
+      - transfers-test
+
+  mysql:
+    image: mysql/mysql-server
+    container_name: mysql
+    # ports:
+    #   - "3306:3306"
+    volumes:
+      # Note: this fixes the permissions issue, but docker-compose up will fail on first attempt
+      - ./docker/sql-init/:/docker-entrypoint-initdb.d/
+    environment:
+      - MYSQL_USER=${DBUSER:-central_ledger}
+      - MYSQL_PASSWORD=${DBPASS:-password}
+      - MYSQL_DATABASE=${DBUSER:-central_ledger}
+      - MYSQL_ALLOW_EMPTY_PASSWORD=true
+    networks:
+      - mojaloop-net
+    healthcheck:
+      test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql"]
+      timeout: 20s
+      retries: 10
+      start_period: 40s
+      interval: 30s
+    profiles:
+      - central-ledger
+      - transfer
+      - discovery
+      - agreement
+      - all-services
+      - transfers-test
+
+  ml-api-adapter:
+    image: mojaloop/ml-api-adapter:${ML_API_ADAPTER_VERSION}
+    container_name: ml-api-adapter
+    command: sh -c "/opt/app/config-modifier/run.js /opt/app/config/default.json /opt/app/config-modifier/configs/ml-api-adapter.js /opt/app/config/default.json && /opt/app/wait4/wait4.js ml-api-adapter && node src/api/index.js"
+    # ports:
+    #   - "3000:3000"
+    volumes:
+      - ./docker/wait4:/opt/app/wait4
+      - ./docker/config-modifier:/opt/app/config-modifier
+    environment:
+      - LOG_LEVEL=info
+      - EVENT_SDK_TRACEID_PER_VENDOR=false
+    networks:
+      - mojaloop-net
+    depends_on:
+      kafka:
+        condition: service_started
+      central-ledger:
+        condition: service_started
+    healthcheck:
+      test: wget -q http://localhost:3000/health -O /dev/null || exit 1
+      timeout: 30s
+      retries: 30
+      interval: 30s
+      start_period: 30s
+    user: root
+    profiles:
+      - ml-api-adapter
+      - transfer
+      - all-services
+      - transfers-test
 
   ## Testing Toolkit
   mojaloop-testing-toolkit:
@@ -116,6 +308,8 @@ services:
     profiles:
       - testing-toolkit
       - all-services
+      - als-test
+      - transfers-test
 
   mojaloop-testing-toolkit-ui:
     image: mojaloop/ml-testing-toolkit-ui:v15.3.0
@@ -135,8 +329,10 @@ services:
     profiles:
       - testing-toolkit
       - all-services
+      - als-test
+      - transfers-test
 
-  ttk-provisioning:
+  ttk-provisioning-als:
     image: mojaloop/ml-testing-toolkit-client-lib:v1.2.0
     env_file:
       - .env
@@ -158,39 +354,33 @@ services:
       - "npm run cli -- -u http://mojaloop-testing-toolkit:5050 -l 2 -i collections/provisioning-perf-als -e environments/default-env.json --save-report --report-format html --report-target file://reports/ttk-provisioning-report.html"
     user: root
     profiles:
-      - ttk-provisioning
+      - ttk-provisioning-als
 
-  ## Generic Callback Handler Service
-  # callback-handler-svc:
-  #   # scale: 1
-  #   scale: 4
-  #   image: mojaloop/callback-handler-svc:local
-  #   env_file:
-  #     - .env
-  #     - perf.env
-  #   build:
-  #     context: ./packages/callback-handler-svc
-  #     cache_from:
-  #       - mojaloop/callback-handler-svc:local
-  #   # ports:
-  #   #   - "3001:3001"
-  #   networks:
-  #     - mojaloop-net
-  #   volumes:
-  #     - ./packages/callback-handler-svc/config:/opt/app/config
-  #     - ./packages/callback-handler-svc/handlers:/opt/app/handlers
-  #   environment:
-  #     - LOG_LEVEL=info
-  #   healthcheck:
-  #     test: wget -q http://localhost:3001/health -O /dev/null || exit 1
-  #     timeout: 20s
-  #     retries: 30
-  #     interval: 15s
-  #   user: root
-  #   profiles:
-  #     - simulators
-  #     - callback-handler
-  #     - all-services
+  ttk-provisioning-transfers:
+    image: mojaloop/ml-testing-toolkit-client-lib:v1.2.0
+    env_file:
+      - .env
+      - perf.env
+    volumes:
+      - "./docker/ml-testing-toolkit/test-cases/collections:/opt/app/collections"
+      - "./docker/ml-testing-toolkit/test-cases/environments:/opt/app/environments"
+      - "./reports:/opt/app/reports"
+    depends_on:
+      mojaloop-testing-toolkit:
+        condition: service_healthy
+      ml-api-adapter:
+        condition: service_healthy
+      central-ledger:
+        condition: service_healthy
+    networks:
+      - mojaloop-net
+    command:
+      - sh
+      - -c
+      - "npm run cli -- -u http://mojaloop-testing-toolkit:5050 -l 2 -i collections/provisioning -e environments/default-env.json --save-report --report-format html --report-target file://reports/ttk-provisioning-report.html"
+    user: root
+    profiles:
+      - ttk-provisioning-transfers
 
   callback-handler-svc-oracle-sim:
     scale: 1
@@ -221,6 +411,7 @@ services:
       - simulators
       - callback-handler
       - all-services
+      - als-test
 
   callback-handler-svc-cl-sim:
     scale: 1
@@ -251,6 +442,7 @@ services:
       - simulators
       - callback-handler
       - all-services
+      - als-test
 
   callback-handler-svc-payee-sim:
     scale: 1
@@ -281,6 +473,7 @@ services:
       - simulators
       - callback-handler
       - all-services
+      - als-test
       - 2dfsp
       - 4dfsp
       - 8dfsp
@@ -399,6 +592,7 @@ services:
       - simulators
       - callback-handler
       - all-services
+      - als-test
       - 2dfsp
       - 4dfsp
       - 8dfsp
